"""Modular Item Effects, Procedural Consumable Generators & Target Application Engine."""
from .metadata import (
    POTION_PURPOSE_TAGS,
    POTION_EFFECT_TAGS,
    FOOD_TASTE_TAGS,
    FOOD_EFFECT_TAGS,
    DRINK_TASTE_TAGS,
    DRINK_EFFECT_TAGS,
    POTION_SCALING,
    FOOD_SCALING,
    DRINK_SCALING,
    serialize_consumable_metadata,
    parse_consumable_metadata,
    serialize_digital_item_metadata,
    parse_digital_item_metadata,
    is_digital_item,
    create_digital_media_item,
    normalize_consumable_scenario,
    parse_item_tier,
    is_key_item,
    is_giftable_item,
    parse_item_effect,
)
from .generators import (
    generate_potion_name,
    generate_food_name,
    generate_drink_name,
    generate_procedural_potion,
    generate_procedural_food,
    generate_procedural_drink,
    classify_and_enrich_ad_hoc_item,
)
from .usage import (
    evaluate_gift_reaction,
    apply_item_to_target,
)

__all__ = [
    "POTION_PURPOSE_TAGS",
    "POTION_EFFECT_TAGS",
    "FOOD_TASTE_TAGS",
    "FOOD_EFFECT_TAGS",
    "DRINK_TASTE_TAGS",
    "DRINK_EFFECT_TAGS",
    "POTION_SCALING",
    "FOOD_SCALING",
    "DRINK_SCALING",
    "serialize_consumable_metadata",
    "parse_consumable_metadata",
    "serialize_digital_item_metadata",
    "parse_digital_item_metadata",
    "is_digital_item",
    "create_digital_media_item",
    "normalize_consumable_scenario",
    "parse_item_tier",
    "is_key_item",
    "is_giftable_item",
    "parse_item_effect",
    "generate_potion_name",
    "generate_food_name",
    "generate_drink_name",
    "generate_procedural_potion",
    "generate_procedural_food",
    "generate_procedural_drink",
    "classify_and_enrich_ad_hoc_item",
    "evaluate_gift_reaction",
    "apply_item_to_target",
]
